apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-prometheus-rule
  labels:
    release: prometheus # Label for release association
spec:
  groups:
    - name: api # Name of the rule group
      rules:
        - alert: down # Alert name
          expr: up == 0 # Expression to trigger the alert when 'up' is equal to 0
          for: 0m # Minimum duration for which the alert condition must be true to trigger the alert
          labels:
            severity: Critical # Label indicating the severity of the alert
          annotations:
            summary: Prometheus target missing {{$labels.instance}}
